parameters:
- name: environment
  type: string
  default: 'Kritikos IO'
- name: jobName
  type: string
  default: kritikos-io
- name: packagesToPush
  type: string
  default: '*.nupkg'
- name: feedName
  type: string
  default: NugetKritikos
- name: artifact
  type: string
  default: nuget
- name: tagOnGit
  type: boolean
  default: false
- name: gitHubConnection
  type: string
- name: isPreRelease
  type: boolean
  default: true

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Push nugets to ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
          - download: current
            artifact: ${{ parameters.artifact }}
            displayName: Downloads packed artifact
          - download: current
            artifact: AssemblyInfo
            displayName: Downloads AssemblyInfo for git changelog
          - ${{ if and(parameters.tagOnGit,or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),eq(variables['Build.SourceBranch'], 'refs/heads/main')))) }}:
            - template: ../../steps/general/12. github-release.yml
              parameters:
                gitHubConnection: ${{ parameters.gitHubConnection }}
                publishedArtifact: ${{ parameters.artifact }}
                isPreRelease: ${{ parameters.isPreRelease }}
                publshFileType: '*.nupkg'
          - template: ../../steps/nuget/01. nuget-push.yml
            parameters:
              packagesToPush: $(Pipeline.Workspace)/${{ parameters.artifact }}/${{ parameters.packagesToPush }}
              feedName: ${{ parameters.feedName }}
