steps:
- bash: |-
    echo "Current branch is: $Build_SourceBranch"
    if [ "$Build_SourceBranch" -eq "refs/heads/master" ] || [ "$Build_SourceBranch" -eq "refs/heads/master" ]
    then
      TAG=`git describe --tags --abbrev=0 --exclude "v*-*"`
    else
      TAG=`git describe --tags --abbrev=0`
    fi

    if [ "$?" -eq 0 ]
    then
      echo "Found tag $TAG"
      git log --format=format:"- %s" --no-merges $TAG..HEAD > $(Build.ArtifactStagingDirectory)/changes.log
    else
      git log --format=format:"- %s" --no-merges > $(Build.ArtifactStagingDirectory)/changes.log
    fi

    echo $'\n\nEmoji legend available at https://gitmoji.dev' >> $(Build.ArtifactStagingDirectory)/changes.log
  displayName: Set changelog from git history
