parameters:
- name: gitHubConnection
  type: string
- name: publishedArtifact
  type: string
- name: isPreRelease
  type: boolean
  default: true
- name: publshFileType
  type: string

steps:
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: ${{ parameters.gitHubConnection }}
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(Build.BuildNumber)'
      title: 'Version $(Build.BuildNumber)'
      releaseNotesFilePath: '$(Pipeline.Workspace)/AssemblyInfo/changes.log'
      assets: '$(Pipeline.Workspace)/${{ parameters.publishedArtifact }}/${{ parameters.publshFileType }}'
      isDraft: $(ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      isPreRelease: ${{ parameters.isPreRelease }}
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
    displayName: Create Github Release
